version: '3'

services:
  postgres:
    image: postgres:alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password # Stored in systems paramter store if production configuration
      - APP_DB_USER=postgres
      - APP_DB_PASS=password # Stored in systems paramter store if production configuration
      - APP_DB_NAME=dataminr
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
      